# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Aires' do
    pod 'SwiftCharts', '~> 0.2'
    pod 'Alamofire', '~> 2.0.2'
end

